### ISSUE TITLE
About the trained model

### ISSUE THREAD

**Issue by ysc703** [YirongMao/COSONet#1]
Hi,
Thanks for release the code.
It is said that the trained models are available. But in the given link of BaiduYun, there are only the datasets. I haven't download the files as the low download speed of it. 

Thanks!

**Comment by YirongMao** [comment]
> Hi,
> Thanks for release the code.
> It is said that the trained models are available. But in the given link of BaiduYun, there are only the datasets. I haven't download the files as the low download speed of it.
> 
> Thanks!
The trained model is in 'WebFace.tar' which includes the pre-processed dataset and trained models.

**Comment by ysc703** [comment]
@YirongMao Thanks!
