### ISSUE TITLE
Google Drive Link for Data and model

### ISSUE THREAD

**Issue by NU9833** [YirongMao/COSONet#2]
Hi,

Can you kindly create a google drive/ one drive link (or any other suitable platform) for data and models as I cannot download from Baidu from outside China?

Thanks in advance.

**Comment by YirongMao** [comment]
> Hi,
> 
> Can you kindly create a google drive/ one drive link (or any other suitable platform) for data and models as I cannot download from Baidu from outside China?
> 
> Thanks in advance.

Thanks for your interest. You can email me.
